name: fomo_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.8
  - pip
  - setuptools
  - wheel
  - cuda-toolkit=12.1
  - pip:
    - torch==2.2.2
    - torchvision==0.17.2
    - torchaudio==2.2.2
    - lightning>=2.1.4
    - numpy>=1.23
    - yucca==2.2.6
    - opencv-python>=4.8.1.78
    - einops>=0.7
    - nnunetv2>=2.4.2
    - wandb>=0.16.0